all: udivtotal32 udivtotal4 uremtotal32 uremtotal4 

udivtotal32: udivtotal32.cpp
udivtotal4: udivtotal4.cpp
uremtotal32: uremtotal32.cpp 
uremtotal4: uremtotal4.cpp 


clean :
	rm udivtotal32 udivtotal4 uremtotal32 uremtotal4